### ISSUE TITLE
Midnight Mushrooms wont grow into their structure versions if bonemealed on certain blocks

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/Midnight#22]
If you bone meal, lets say a viridshroom, on midnight soil or midnight grass, it because the large blocky version, however even though it can be placed on normal minecraft grass or even nightstone which it naturally generates on anyways, if placed on these blocks bonemealing it will only eat your bone meal, and it will never go into the structure form

**Comment by gegy1000** [comment]
I suppose this is related to #21. Midnight Mushrooms only grow on Midnight Soil or Grass. I don't think it makes sense for them to grow on other blocks. Thoughts?

**Comment by Terenx** [comment]
They do spawn naturally and frequently underground on top of nightstone, and can be placed directly on nightstone, yet dispite nightstone being “soil” for the mushrooms, they cannot be turned into the blocky form, and if they can be placed on grass blocks, why can they not be placed on mycelium, a block made for growing mushrooms

**Comment by gegy1000** [comment]
Ah right, for nightstone this is an issue. Mycelium probably makes sense to support.
