### ISSUE TITLE
Portal spawning range

### ISSUE THREAD

**Issue by MelanX** [Cryptic-Mushroom/Midnight#29]
Is it possible to let the portal spawn like mobs with a min range?
Clearly: 
mobs only spawn >24 blocks from the player
portals should do something like this, too (or adjustable in config)
because I was just running and then.. a portal in front of me and no chance to react :D

**Comment by gegy1000** [comment]
Spawn rates of rifts are also currently too common, and should only spawn where there is no light.

**Comment by MelanX** [comment]
Yeah I was running in through the darkness
