### ISSUE TITLE
Crash when playing to spam the command : "/tp @e @a"

### ISSUE THREAD

**Issue by arthurbambou** [Cryptic-Mushroom/Midnight#31]
Crash report link :
https://gist.github.com/arthurbambou/e47508ee042d497eef0d6b19ed7d62f3

**Comment by Terenx** [comment]
That just happens in vanilla too, your teleporting every fudging entity to a single point, you.

**Comment by arthurbambou** [comment]
ok

**Comment by gegy1000** [comment]
Thanks for the report! This has been resolved already, just not released yet.

**Comment by arthurbambou** [comment]
ok nice :-)

**Comment by Terenx** [comment]
Nvm it’s probably you teleporting the rift as well and it all being teleported or even a rift being teleported by a rift
