### ISSUE TITLE
Rifts move sleeping player models into them, but do not teleport them

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/Midnight#32]
if you are sleeping too close to a rift (why would you), if they are closing before it ticks to day and you cant sleep again, your player model will be sucked torwards or even into the rift, but you do not get teleported, and rifts can teleport sleeping player models, if you put the head of the bed inside of a rift clicking on the bed to sleep will immediately teleport you to the midnight, please make them teleport or leave slumber alone

**Comment by gegy1000** [comment]
Heh. That's a fun one.

**Comment by Terenx** [comment]
If you have ever played tf2 you can just slap a nope onto every time your character just pops back into the bed, also never get 5 command blocks, set then up to a super fast red stone clock, have it daytime, and have em all spawn rifts, anything that is not outside its range or without ample cover is sucked in at the speed of sound, not even flash can escape it, and help your computer’s soul if you add more and it becomes night with all those particles

**Comment by gegy1000** [comment]
Closed in https://github.com/Cryptic-Mushroom/Midnight/commit/4d576ca17147ae922c7616664fa33b99334a1fd9

**Comment by Terenx** [comment]
That works, maybe make it say “You cannot sleep now, There is an evil presence nearby”

**Comment by Martacus** [comment]
Well, your sleep gets cancelled as soon as you get grabbed. So saying that doesnt really make sense :p
