### ISSUE TITLE
The hats of giant mushroom structures created in 0.1.0 are deleted upon updating to 0.1.1

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/Midnight#43]

**Comment by gegy1000** [comment]
I think it's fair to say for an alpha that things will break.

**Comment by Terenx** [comment]
In servers updating it makes all the hat blocks take on the texture that makes every side the outward side

**Comment by gegy1000** [comment]
Going to close this as unfortunately version to version compatibility is not something we're focusing on yet.
