### ISSUE TITLE
Midnight doors do not auto-align with Overworld doors

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/Midnight#45]
Ik this is kinda trivial, the overworld and the midnight are supposed to be opposite and who the heck is gonna put a dull brown door right next to a lovely dark blue one but still, doors are doors, and if all overworld doors align with themselves and all midnight doors align with themselves, and they both have pretty much the same coding, why dont overworld doors and midnight doors align aswell?

**Comment by gegy1000** [comment]
Due to silly vanilla hardcoding this can't be change on vanilla doors. However, it can be made so midnight doors align with vanilla's.
