### ISSUE TITLE
Rifters should have a damage threshold before dropping something and have arrow immunity while dragging

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/Midnight#52]
rifters drop whatever they are holding if they take ANY damage, even damage that doesn't actually do damage, you could literally escape their grasp by just tossing an egg or snowball while being dragged, and since the rifters speed is slow, you could easily outrun them even with slowness 3 from their drag! I believe rifters should have a damage threshold before dropping something, kinda like in D&D if someone does enough damage while in the gullet of an enemy, the enemy regurgitates the player, keyword, ENOUGH damage. rifters should probably take at least 4 damage before dropping something, and maybe to rebalance, maybe make them passively regain health while within 20 blocks of a rift and inside the midnight, and to keep from people just spamming bows or a skeleton shooting at the player and hitting the rifter, maybe give them arrow immunity as a passive or while dragging, arrow immunity will definitely make them harder and keep people from just spamming bows. (p.s. you dont need to change enderpearls, they can be nullified by the damage threshold and trying to toss them anywhere but the rifter will just eat the pearl and won't move you)

**Comment by AndrewReneGerard** [comment]
Your going to play Warhammer, not D&D, your reading a book on how to play it every night, wait, uhhhhhhhhhhhhhhhhhh
