### ISSUE TITLE
planting seeds on nightstones

### ISSUE THREAD

**Issue by InfiniteSkyrootLizard** [Cryptic-Mushroom/Midnight#58]
eh well, I can place seeds on nightstones and on midnight dirt/grass

![2018-11-02_23 47 36](https://user-images.githubusercontent.com/44714743/47944691-49242d80-defd-11e8-8882-91ee888e21d2.png)

**Comment by Terenx** [comment]
Check #34 I already posted this bug, you can add a comment saying which also you can plant on, or if gegy allows it, this can be separate

**Comment by gegy1000** [comment]
Thanks for the report! Going to close this post the screenshot in the other issue. :)
