### ISSUE TITLE
Shadowroot Leaves and Midnight Grass change color based on the biome they are in only in the midnight, and dark willow leaves don't.

### ISSUE THREAD

**Issue by Terenx** [Cryptic-Mushroom/Midnight#64]
When going from 0.1.1 to the snapshot build the molten crater biomes were removed and replaced with the default plains biome, along with overworld mobs spawning in that molten crater, on the edges for some reason the midnight grass and shadowroot leaves turns a lush green, but doesn't do that in the overworld, and dark willow trees seem unaffected   Edit:Midnight grass and midnight double tall grass also changes color, go figure
![2018-11-20_11 45 21](https://user-images.githubusercontent.com/44249598/48792418-d74c3200-ecb9-11e8-853f-7ba96a6b98ac.png)

**Comment by gegy1000** [comment]
Dark Willow not being affected is intentional. I believe this is safe to ignore, as normally you would not find non-midnight biomes in the midnight dimension.
